
version: "3"

services:

  database:

    image: "postgres:latest"


    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: gokul # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: gokul # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: postgres # The PostgreSQL default database (automatically created at first launch)


    volumes:

      - ./db-data/:/var/lib/postgresql/data/